const LanguageData = {
  en: {
    dashboard: "Dashboard",
    home: "HomeDash",
    inbox: "Inbox",
    reports: "All Reports",
    settings: "Settings",
    userprofile: "User Profile",
    teams: "Our Team",
    support: "Support",
    faq: "FAQ",
    enquiry: "General Enquiry",
    tickets: "Tickets",
    logout: "Logout",
    welcome: "Welcome Admin",
    totalUsers: "Total Users",
    pendingUsers: "Pending Users",
    ongoingTasks: "Ongoing Tasks",
    pendingTasks: "Pending Tasks",
    monthlySales: "Monthly Sales",
    unitsSold: "Units Sold",
    search: "Search...",
    teamMembers: "Team Members",
    teamDescription: "Manage your team and roles",
    
    profile: "Profile",
    role: "Role",
    location: "Location",
    personalInformation: "Personal Information",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    phone: "Phone",
    bio: "Bio",
    address: "Address",
    country: "Country",
    cityState: "City / State",
    postalCode: "Postal Code",
    edit: "Edit",
    socialInstagram: "Instagram",
    socialLinkedIn: "LinkedIn",
    socialWhatsApp: "WhatsApp"
  },

  hi: {
    dashboard: "डैशबोर्ड",
    home: "होम",
    inbox: "इनबॉक्स",
    reports: "सभी रिपोर्ट",
    settings: "सेटिंग्स",
    userprofile: "यूज़र प्रोफाइल",
    teams: "हमारी टीम",
    support: "सहायता",
    faq: "अक्सर पूछे जाने वाले प्रश्न",
    enquiry: "सामान्य पूछताछ",
    tickets: "टिकट",
    logout: "लॉगआउट",
    welcome: "स्वागत है एडमिन",
    totalUsers: "कुल उपयोगकर्ता",
    pendingUsers: "लंबित उपयोगकर्ता",
    ongoingTasks: "चल रहे कार्य",
    pendingTasks: "लंबित कार्य",
    monthlySales: "मासिक बिक्री",
    unitsSold: "बेची गई इकाइयाँ",
    search: "खोजें...",
    teamMembers: "टीम के सदस्य",
    teamDescription: "अपनी टीम और भूमिकाओं का प्रबंधन करें",

    profile: "प्रोफ़ाइल",
    role: "भूमिका",
    location: "स्थान",
    personalInformation: "व्यक्तिगत जानकारी",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    email: "ईमेल",
    phone: "फ़ोन",
    bio: "जीवनी",
    address: "पता",
    country: "देश",
    cityState: "शहर / राज्य",
    postalCode: "पिन कोड",
    edit: "संपादित करें",
    socialInstagram: "इंस्टाग्राम",
    socialLinkedIn: "लिंक्डइन",
    socialWhatsApp: "व्हाट्सएप"
  },

  pa: {
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    home: "ਹੋਮ",
    inbox: "ਇਨਬਾਕਸ",
    reports: "ਸਭ ਰਿਪੋਰਟਾਂ",
    settings: "ਸੈਟਿੰਗਾਂ",
    userprofile: "ਯੂਜ਼ਰ ਪ੍ਰੋਫ਼ਾਈਲ",
    teams: "ਸਾਡੀ ਟੀਮ",
    support: "ਸਹਾਇਤਾ",
    faq: "ਅਕਸਰ ਪੁੱਛੇ ਸਵਾਲ",
    enquiry: "ਆਮ ਪੁੱਛਗਿੱਛ",
    tickets: "ਟਿਕਟਾਂ",
    logout: "ਲੌਗਆਉਟ",
    welcome: "ਸੁਆਗਤ ਹੈ ਐਡਮਿਨ",
    totalUsers: "ਕੁੱਲ ਯੂਜ਼ਰ",
    pendingUsers: "ਲੰਬਿਤ ਯੂਜ਼ਰ",
    ongoingTasks: "ਚੱਲ ਰਹੇ ਕੰਮ",
    pendingTasks: "ਲੰਬਿਤ ਕੰਮ",
    monthlySales: "ਮਹੀਨਾਵਾਰ ਵਿਕਰੀ",
    unitsSold: "ਵੇਚੀਆਂ ਇਕਾਈਆਂ",
    search: "ਖੋਜੋ...",
    teamMembers: "ਟੀਮ ਮੈਂਬਰ",
    teamDescription: "ਆਪਣੀ ਟੀਮ ਅਤੇ ਭੂਮਿਕਾਵਾਂ ਨੂੰ ਪ੍ਰਬੰਧਿਤ ਕਰੋ",

    profile: "ਪ੍ਰੋਫ਼ਾਈਲ",
    role: "ਭੂਮਿਕਾ",
    location: "ਟਿਕਾਣਾ",
    personalInformation: "ਨਿੱਜੀ ਜਾਣਕਾਰੀ",
    firstName: "ਪਹਿਲਾ ਨਾਮ",
    lastName: "ਆਖਰੀ ਨਾਮ",
    email: "ਈਮੇਲ",
    phone: "ਫ਼ੋਨ",
    bio: "ਜੀਵਨੀ",
    address: "ਪਤਾ",
    country: "ਦੇਸ਼",
    cityState: "ਸ਼ਹਿਰ / ਰਾਜ",
    postalCode: "ਪੋਸਟਲ ਕੋਡ",
    edit: "ਸੰਪਾਦਿਤ ਕਰੋ",
    socialInstagram: "ਇੰਸਟਾਗ੍ਰਾਮ",
    socialLinkedIn: "ਲਿੰਕਡਇਨ",
    socialWhatsApp: "ਵਟਸਐਪ"
  },

  fr: {
    dashboard: "Tableau de bord",
    home: "Accueil",
    inbox: "Boîte de réception",
    reports: "Tous les rapports",
    settings: "Paramètres",
    userprofile: "Profil utilisateur",
    teams: "Notre équipe",
    support: "Support",
    faq: "FAQ",
    enquiry: "Demande générale",
    tickets: "Tickets",
    logout: "Déconnexion",
    welcome: "Bienvenue Admin",
    totalUsers: "Utilisateurs totaux",
    pendingUsers: "Utilisateurs en attente",
    ongoingTasks: "Tâches en cours",
    pendingTasks: "Tâches en attente",
    monthlySales: "Ventes mensuelles",
    unitsSold: "Unités vendues",
    search: "Recherche...",
    teamMembers: "Membres de l'équipe",
    teamDescription: "Gérez votre équipe et ses rôles",

    profile: "Profil",
    role: "Rôle",
    location: "Emplacement",
    personalInformation: "Informations personnelles",
    firstName: "Prénom",
    lastName: "Nom de famille",
    email: "Email",
    phone: "Téléphone",
    bio: "Bio",
    address: "Adresse",
    country: "Pays",
    cityState: "Ville / État",
    postalCode: "Code postal",
    edit: "Modifier",
    socialInstagram: "Instagram",
    socialLinkedIn: "LinkedIn",
    socialWhatsApp: "WhatsApp"
  },

  au: {
    dashboard: "Dashboard",
    home: "Home",
    inbox: "Inbox",
    reports: "All Reports",
    settings: "Settings",
    userprofile: "User Profile",
    teams: "Our Team",
    support: "Support",
    faq: "FAQ",
    enquiry: "General Enquiry",
    tickets: "Tickets",
    logout: "Logout",
    welcome: "Welcome Admin",
    totalUsers: "Total Users",
    pendingUsers: "Pending Users",
    ongoingTasks: "Ongoing Tasks",
    pendingTasks: "Pending Tasks",
    monthlySales: "Monthly Sales",
    unitsSold: "Units Sold",
    search: "Search...",
    teamMembers: "Team Members",
    teamDescription: "Manage your team and roles",
    profile: "Profile",
    role: "Role",
    location: "Location",
    personalInformation: "Personal Information",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    phone: "Phone",
    bio: "Bio",
    address: "Address",
    country: "Country",
    cityState: "City / State",
    postalCode: "Postal Code",
    edit: "Edit",
    socialInstagram: "Instagram",
    socialLinkedIn: "LinkedIn",
    socialWhatsApp: "WhatsApp"
  }
};

export default LanguageData;
